// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZ_pyc-h7hjeVI7S5LnO1-9IBz2P0Oms',
    appId: '1:293687363588:web:632ab6c696909701574d51',
    messagingSenderId: '293687363588',
    projectId: 'notes-5cbff',
    authDomain: 'notes-5cbff.firebaseapp.com',
    storageBucket: 'notes-5cbff.firebasestorage.app',
    measurementId: 'G-44MNP77YTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjngvzw9Pne9NfBzBNoyc04qLs91oJje8',
    appId: '1:293687363588:android:83d4cdbbb0e411d2574d51',
    messagingSenderId: '293687363588',
    projectId: 'notes-5cbff',
    storageBucket: 'notes-5cbff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRq55H6snlD43FiJMG3vgsPCxPH5bY-4',
    appId: '1:293687363588:ios:8e8d593ab977690c574d51',
    messagingSenderId: '293687363588',
    projectId: 'notes-5cbff',
    storageBucket: 'notes-5cbff.firebasestorage.app',
    iosBundleId: 'com.example.thirdFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQRq55H6snlD43FiJMG3vgsPCxPH5bY-4',
    appId: '1:293687363588:ios:8e8d593ab977690c574d51',
    messagingSenderId: '293687363588',
    projectId: 'notes-5cbff',
    storageBucket: 'notes-5cbff.firebasestorage.app',
    iosBundleId: 'com.example.thirdFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsZ_pyc-h7hjeVI7S5LnO1-9IBz2P0Oms',
    appId: '1:293687363588:web:c8a211a28b1c0156574d51',
    messagingSenderId: '293687363588',
    projectId: 'notes-5cbff',
    authDomain: 'notes-5cbff.firebaseapp.com',
    storageBucket: 'notes-5cbff.firebasestorage.app',
    measurementId: 'G-GH81FZCDBE',
  );
}
